version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
           name: Restore Yarn Package Cache
           keys:
             - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules

  type-check:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Type check
          command: yarn run type-check

  lint:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Lint
          command: yarn run lint

  build:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Gatsby build
          command: DISABLE_WEBPACK_BUNDLE_ANALYSER=1 yarn run build
      - persist_to_workspace:
          root: ./
          paths:
            - example/public/
  deploy-pr-preview:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Preview deploy
          command: npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir=example/public
  deploy-master:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Production deploy
          command: npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=example/public
  release:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: release
          command: yarn run semantic-release

workflows:
  version: 2
  build_and_test: # name of your workflow
    jobs:
      - install:
          filters:
            branches:
              ignore:
                - size-plugin-*
      - type-check:
          requires:
            - install
          filters:
            branches:
              ignore:
                - size-plugin-*
      - lint:
          requires:
            - install
          filters:
            branches:
              ignore:
                - size-plugin-*
      - build:
          requires:
            - lint
            - type-check
          filters:
            branches:
              ignore:
                - size-plugin-*
      - deploy-pr-preview:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
                - size-plugin-*
      - deploy-master:
          requires:
            - build
          filters:
            branches:
             only:
                - master
      - release:
          requires:
            - deploy-master
          filters:
            branches:
             only:
                - master
